fix(): Squashed commit of the following:
commit 2881e4367acac78af6356e1f276f7880e234143e
Author: terjos <terjos@neuf.fr>
Date:   Tue Apr 19 11:51:29 2022 +0200

    fix(admin reservation): edit filter

commit 89214d23b6e35530fe5c337db86d75ec3e99b5a2
Author: terjos <terjos@neuf.fr>
Date:   Tue Apr 19 10:49:32 2022 +0200

    fix(Admin creat user): hash password before save

commit eb39403a3d1699539fd64289e06a3f5bf2ae0da5
Author: terjos <terjos@neuf.fr>
Date:   Tue Apr 19 08:45:55 2022 +0200

    fix(html css): validate W3C

commit 7d8a5eebd935fd7d7eba7fbd5e43eb1695dea170
Author: terjos <terjos@neuf.fr>
Date:   Mon Apr 18 16:21:45 2022 +0200

    feat(link): add logout in account and home in admin

commit 45cf5392a0563ee7220821d032b4ffa27be7bcbc
Author: terjos <terjos@neuf.fr>
Date:   Mon Apr 18 15:44:23 2022 +0200

    fixup(User): add Serializable

    as a manager when changing the image of an establishment

    ERROR: Serialization of 'Symfony\Component\HttpFoundation\File\File' is not allowed

commit fc442637c8a7828e60afd68618c5bb5d3251431c
Author: terjos <terjos@neuf.fr>
Date:   Mon Apr 18 15:25:44 2022 +0200

    fixup(CRUD User): remove adress cp and city of form

commit df512b1ca06cb57089e2f7fa6c42383e574eba0c
Author: terjos <terjos@neuf.fr>
Date:   Mon Apr 18 10:23:35 2022 +0200

    feat(Footer): add footer

commit 3ae108eda79e783d8a40edce30fee40a6d058c16
Author: terjos <terjos@neuf.fr>
Date:   Mon Apr 18 10:15:01 2022 +0200

    feat(Error): Overriding the Default Error Templates

commit 27b8094de9e84a711197b28a18da91ca8c2c218c
Author: terjos <terjos@neuf.fr>
Date:   Mon Apr 18 09:55:05 2022 +0200

    style(php files): add php-cs

commit fee8d57aaa1e9dbe8f8df553bd7c9935eee44b82
Author: terjos <terjos@neuf.fr>
Date:   Mon Apr 18 09:20:15 2022 +0200

    style(Twig files): unify the indentation

commit 2ae548391e4a05269d936a5e5d672d06d5287506
Author: terjos <terjos@neuf.fr>
Date:   Mon Apr 18 08:55:30 2022 +0200

    fix(Header): change title and add meta description